# Generated by Django 4.0.3 on 2022-03-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=255, verbose_name='Фио читателя')),
                ('eticket', models.CharField(blank=True, max_length=13, verbose_name='Читательский билет')),
                ('phone', models.CharField(blank=True, max_length=18, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Читатель',
                'verbose_name_plural': 'Читатели',
            },
        ),
    ]
